spring:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  #模板引擎配置
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    check-template-location: true
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    #表示将Spring的RequestContextAttribute对象暴露为变量request,用于获取项目路径
    request-context-attribute: request
    suffix: .html
    template-loader-path: classpath:/templates/  #表示所有的模板文件都放在该目录下
    settings:
      locale: zh_CN
      number_format: 0.######
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
      #不能配置成true,false抛异常
      boolean_format: yes,no
